=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Server.Engineering.22.0.7198/runtimes/win-x64/native/ExtensionSettings.Schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "visibility": {
      "type": "string",
      "enum": [
        "AlwaysShow",
        "AlwaysHide",
        "HideInEngineering"
      ],
      "default": "AlwaysShow"
    },
    "serverSymbol": {
      "allOf": [
        {
          "$ref": "http://json-schema.org/draft-04/schema#"
        },
        {
          "type": "object",
          "properties": {
            "function": {
              "type": "boolean",
              "description": "true to declare this symbol as a function."
            }
          }
        }
      ]
    },
    "symbolVersionHistory": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "description": "Description of the symbol."
        },
        "sample": {
          "description": "Sample value for the WriteValue. Can be used for documentation.",
          "type": "object",
          "properties": {
            "description": {
              "description": "A description of this sample."
            },
            "value": {
              "description": "The 'writeValue' for the command."
            },
            "filter": {
              "description": "A filter for the command."
            },
            "path": {
              "description": "A sub-path for the command."
            },
            "requestType": {
              "description": "The request type for the sample request."
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "$schema": {
      "type": "string"
    },
    "policies": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "StrictPropertyValidation",
          "StrictConfigListenerFilter"
        ]
      },
      "description": "StrictPropertyValidation: when not set, functions without writeValue will accept any input\nStrictConfigListenerFilter: when multiple config values are changed at once, pass only those configuration values to the config listener of the corresponding server extension that match the specified filter; otherwise, all changed configuration values are passed to the config listener of the corresponding server extension if any of them matches the specified filter."
    },
    "guid": {
      "type": "string"
    },
    "visibility": {
      "allOf": [
        {
          "$ref": "#/definitions/visibility"
        },
        {
          "description": "Indicates under which circumstances the extension config should be visible."
        }
      ]
    },
    "version": {
      "type": "string",
      "format": "version",
      "description": "Version of the extension library."
    },
    "configVersion": {
      "type": "string",
      "format": "version",
      "description": "Version of the configuration file."
    },
    "packageVersion": {
      "type": "string",
      "description": "Version of the NuGet package that contains the extension."
    },
    "productVersion": {
      "type": "string",
      "format": "version",
      "description": "Version of the TwinCAT HMI with which the extension was created."
    },
    "dotNetTargetFramework": {
      "type": "string",
      "description": "The .NET target framework. (This property is set automatically during the build - do not set it manually.)"
    },
    "dotNetTargetFrameworkVersion": {
      "type": "string",
      "description": "Version of the .NET target framework. (This property is set automatically during the build - do not set it manually.)"
    },
    "dotNetPlatformTarget": {
      "type": "string",
      "enum": [
        "AnyCPU",
        "x86",
        "x64"
      ],
      "default": "AnyCPU",
      "description": ".NET platform target. (This property is set automatically during the build - do not set it manually.)"
    },
    "dotNetConfiguration": {
      "type": "string",
      "description": "Configuration of the .NET server extension. (This property is set automatically during the build - do not set it manually.)"
    },
    "signature": {
      "type": "string",
      "format": "base64"
    },
    "signatureData": {
      "type": "string",
      "format": "base64"
    },
    "signatureTcHmiSrvExt": {
      "type": "string",
      "format": "base64"
    },
    "signatureTcHmiSrvExtNet": {
      "type": "string",
      "format": "base64"
    },
    "fileExtensions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "fileExtension": {
            "type": "string",
            "description": "Extension of the file."
          },
          "fileDescription": {
            "type": "string",
            "description": "Language variable describing the file extension."
          }
        },
        "additionalProperties": false
      },
      "description": "File extensions are used by script extensions."
    },
    "symbolCategories": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "localization": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "localization"
        ]
      }
    },
    "symbols": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "readValue": {
            "allOf": [
              {
                "$ref": "#/definitions/serverSymbol",
                "description": "Output parameters of the symbol."
              },
              {
                "type": "object",
                "properties": {
                  "readOnly": {
                    "type": "boolean",
                    "description": "true to declare this symbol as read-only."
                  }
                }
              }
            ]
          },
          "writeValue": {
            "$ref": "#/definitions/serverSymbol",
            "description": "Input parameters of the symbol."
          },
          "addSymbol": {
            "type": "boolean",
            "default": true,
            "description": "true to automatically map this symbol."
          },
          "automap": {
            "type": "boolean",
            "default": true,
            "description": "true to automatically map this symbol. Deprecated, use addSymbol instead."
          },
          "hidden": {
            "type": "boolean",
            "default": true,
            "description": "true to hide this symbol in symbol browser and on the configuration page."
          },
          "visibility": {
            "allOf": [
              {
                "$ref": "#/definitions/visibility"
              },
              {
                "description": "Visibility of the symbol."
              }
            ]
          },
          "category": {
            "type": "string",
            "description": "Can be used to group related symbols."
          },
          "userGroups": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "object",
                "additionalProperties": {
                  "type": "integer",
                  "default": 3,
                  "enum": [
                    0,
                    1,
                    2,
                    3
                  ],
                  "description": "Access level of the symbol for this user group."
                }
              }
            ]
          },
          "access": {
            "type": "integer",
            "default": 3,
            "enum": [
              0,
              1,
              2,
              3
            ],
            "description": "Default access level of the symbol."
          },
          "doc": {
            "type": "string",
            "description": "THIS PROPERTY IS OBSOLETE. USE PROPERTY 'description' instead."
          },
          "description": {
            "type": "string",
            "description": "Description of the symbol."
          },
          "sample": {
            "description": "Sample value for the WriteValue. Can be used for documentation.",
            "type": "object",
            "properties": {
              "description": {
                "description": "A description of this sample."
              },
              "value": {
                "description": "The 'writeValue' for the command."
              },
              "filter": {
                "description": "A filter for the command."
              },
              "path": {
                "description": "A sub-path for the command."
              },
              "requestType": {
                "description": "The request type for the sample request."
              }
            },
            "additionalProperties": true
          },
          "versions": {
            "type": "object",
            "additionalProperties": {
              "$ref": "#/definitions/symbolVersionHistory"
            }
          }
        },
        "additionalProperties": false
      },
      "description": "List of symbols that the extension supports."
    }
  },
  "required": [
    "guid",
    "version",
    "configVersion"
  ]
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Server.Engineering.22.0.7198/runtimes/win-x64/native/TcHmiUserManagement/TcHmiUserManagement.Config.json
{
  "$schema": "../../TcHmiSrv/schema/ExtensionSettings.Schema.json",
  "version": "14.4.124.0",
  "configVersion": "1.0.1.2",
  "guid": "2E0817F0-DE05-42ED-BAFA-552D96B07127",
  "visibility": "HideInEngineering",
  "policies": [
    "StrictPropertyValidation",
    "StrictConfigListenerFilter"
  ],
  "symbolCategories": [
    {
      "name": "__CUSTOM_CONFIG__",
      "localization": "USERS"
    }
  ],
  "symbols": {
    "GetComplexityRules": {
      "readValue": {
        "function": true,
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "properties": {
            "regex": {
              "type": "string",
              "format": "regex"
            },
            "localizationParameters": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            }
          },
          "required": [
            "regex"
          ]
        }
      }
    },
    "ListUsers": {
      "readValue": {
        "function": true,
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "ListDisabledUsers": {
      "readValue": {
        "function": true,
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "RenameUser": {
      "readValue": {
        "function": true
      },
      "writeValue": {
        "type": "object",
        "properties": {
          "currentUserName": {
            "type": "string",
            "description": "Current name of the user."
          },
          "newUserName": {
            "type": "string",
            "description": "The new name of the user."
          }
        },
        "required": [
          "currentUserName",
          "newUserName"
        ]
      }
    },
    "DisableUser": {
      "readValue": {
        "function": true
      },
      "writeValue": {
        "type": "string",
        "description": "Name of the user."
      }
    },
    "EnableUser": {
      "readValue": {
        "function": true
      },
      "writeValue": {
        "type": "string",
        "description": "Name of the user."
      }
    },
    "RemoveUser": {
      "readValue": {
        "function": true
      },
      "writeValue": {
        "type": "string",
        "description": "Name of the user."
      }
    },
    "AddUser": {
      "readValue": {
        "function": true
      },
      "writeValue": {
        "type": "object",
        "properties": {
          "userName": {
            "type": "string",
            "description": "Name of the user."
          },
          "password": {
            "type": "string",
            "format": "masked",
            "description": "Password of the user. Only a hash will be stored."
          },
          "enabled": {
            "type": "boolean",
            "description": "Indicates if the user can be used or not."
          }
        },
        "required": [
          "userName",
          "password"
        ]
      }
    },
    "ChangePassword": {
      "userGroups": [
        "__SystemUsers"
      ],
      "readValue": {
        "function": true
      },
      "writeValue": {
        "type": "object",
        "properties": {
          "currentPassword": {
            "type": "string",
            "format": "masked"
          },
          "newPassword": {
            "type": "string",
            "format": "masked"
          },
          "twoFactorToken": {
            "type": "string",
            "format": "masked"
          }
        }
      }
    },
    "Disable2FA": {
      "userGroups": [
        "__SystemUsers"
      ],
      "writeValue": {
        "type": "object",
        "properties": {
          "password": {
            "type": "string",
            "format": "masked"
          },
          "twoFactorToken": {
            "type": "string",
            "format": "masked"
          }
        },
        "required": [
          "password",
          "twoFactorToken"
        ]
      },
      "readValue": {
        "function": true,
        "type": "boolean"
      }
    },
    "Reset2FA": {
      "readValue": {
        "function": true,
        "type": "boolean"
      },
      "writeValue": {
        "type": "string"
      }
    },
    "Enable2FA": {
      "userGroups": [
        "__SystemUsers"
      ],
      "readValue": {
        "function": true,
        "type": "boolean"
      },
      "writeValue": {
        "type": "object",
        "properties": {
          "password": {
            "type": "string"
          },
          "secret": {
            "type": "string"
          },
          "twoFactorToken": {
            "type": "string"
          }
        },
        "required": [
          "password",
          "secret",
          "twoFactorToken"
        ]
      }
    },
    "Get2FAStatus": {
      "userGroups": [
        "__SystemUsers"
      ],
      "readValue": {
        "type": "integer",
        "enum": [
          0,
          1,
          2,
          3,
          4
        ],
        "options": [
          {
            "value": 0,
            "label": "2FAEnabled",
            "description": "2FA is enabled."
          },
          {
            "value": 1,
            "label": "2FACanBeEnabled",
            "description": "2FA can be enabled."
          },
          {
            "value": 2,
            "label": "2FACannotBeEnabled",
            "description": "2FA cannot be enabled."
          },
          {
            "value": 3,
            "label": "2FACanBeDisabled",
            "description": "2FA may be disabled."
          },
          {
            "value": 4,
            "label": "2FANotRequired",
            "description": "2FA is enabled but not asked for"
          }
        ]
      }
    }
  },
  "packageVersion": "14.4.124.0",
  "productVersion": "14.4.124.0",
  "signature": "dc9TGsETxIM9D0ZrRuVT3NVNVf6ujPJWhgZktl0bfxIUXuo/X8jpXGTfLb4FAB2w2Ycb1xXGO7Z45x/Zsd7Qupt4Y3m4D/hg+hrEmvACzBr4wnCijHvxxSDSwjOZqZ/6lkb6vLBtXcGIhSPyAk9Ry1Bw1w/Soi9O10Fl48gclflGc+y/udmFkIJPKIM/S4iNdiJK0uC0UWq+W98eNtwBCO4rWv+TwkjvPaH42g3YxF1mlftdkjuOY1R/BTPZCd2axqCuhZK21w8/QzJZy/HZrMGO1NBgJZQvLwSFpmIfYkq09SyXY7OfRHjski0wowjbEFH/WuG/4ycIvFFWRfb62A=="
}
