=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Framework.14.3.229/runtimes/native1.12-tchmi/Schema/FunctionDescription.Schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "URL to a schema file"
        },
        "apiVersion": {
            "description": "API Version",
            "type": "integer"
        },
        "version": {
            "type": "object",
            "description": "Version of the asset.",
            "properties": {
                "full": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "major": {
                    "type": "number",
                    "minimum": 0
                },
                "minor": {
                    "type": "number",
                    "minimum": 0
                },
                "revision": {
                    "type": "number",
                    "minimum": 0
                },
                "build": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "additionalProperties": false,
            "required": ["full", "major", "minor", "revision", "build"]
        },
        "dependencyFiles": {
            "type": "array",
            "description": "All files which will be included in the HTML file of the HMI.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "pattern": "^(?!(/)).*$",
                        "description": "Path to the file with the function directory as base path.",
                        "minLength": 1
                    },
                    "type": {
                        "type": "string",
                        "enum": ["Stylesheet", "JavaScript", "EsModule"],
                        "description": "Type of the function asset. Stylesheet, JavaScript and EsModule are supported."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description of this file."
                    }
                },
                "additionalProperties": false,
                "required": ["name", "type", "description"]
            }
        },
        "function": {
            "type": "object",
            "description": "Description for the function itself.",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The name of the function."
                },
                "namespace": {
                    "type": "string",
                    "description": "The namespace of the function."
                },
                "displayName": {
                    "type": "string",
                    "description": "Name which should be presented the user."
                },
                "visible": {
                    "type": "boolean",
                    "description": "Determine if a function is shown to the user."
                },
                "description": {
                    "type": "string",
                    "description": "A long description of this function."
                },
                "category": {
                    "type": "string",
                    "default": "Other",
                    "description": "Name of the area this function will be listed in the creator."
                },
                "injectContextObject": {
                    "type": "boolean",
                    "description": "Adds a context object to the function as the first parameter."
                },
                "waitMode": {
                    "type": "string",
                    "default": "Synchronous",
                    "enum": ["Synchronous", "Asynchronous"],
                    "description": "Tells the system if the function is finished synchronous or if the user will call a feedback function in the context object of the context object to signal finish."
                },
                "returnValue": {
                    "description": "Return value type as a tchmi reference name or null if the function has no return value.",
                    "anyOf": [
                        {
                            "description": "Return value type as a tchmi reference name.",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "pattern": "^tchmi:",
                                    "description": "Type from the return value."
                                },
                                "description": {
                                    "type": "string",
                                    "description": "A long description of the return value."
                                }
                            },
                            "additionalProperties": false
                        },
                        {
                            "description": "The function has no return value.",
                            "type": "null"
                        }
                    ]
                },
                "arguments": {
                    "type": "array",
                    "description": "Function arguments.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "minLength": 1,
                                "description": "Variable name in the function."
                            },
                            "displayName": {
                                "type": "string",
                                "description": "Name which should be presented the user."
                            },
                            "type": {
                                "type": "string",
                                "minLength": 6,
                                "pattern": "^tchmi:",
                                "description": "Information about the expected type as a tchmi reference name."
                            },
                            "description": {
                                "type": "string",
                                "description": "A long description of this argument."
                            },
                            "required": {
                                "type": "boolean",
                                "description": "This parameter is mandatory for this function."
                            },
                            "bindable": {
                                "type": "boolean",
                                "description": "This parameter can be binded to a symbol."
                            },
                            "allowControlAttributeBindingOptions": {
                                "type": "boolean",
                                "description": "This parameter can have the same binding options as a control attribute."
                            },
                            "allowSymbolReferenceWatchDelegation": {
                                "type": "boolean",
                                "description": "Determines if symbol references injected via this parameter will be watched by the function itself if 'delegatedWatch: true' is defined in the context object when calling the function."
                            },
                            "asReference": {
                                "type": "boolean",
                                "description": "TcHmiCreator ui state. Do not manipulate."
                            },
                            "defaultValue": {
                                "description": "This value will be used as initial value while function is generated in engineering."
                            },
                            "restParameter": {
                                "type": "boolean",
                                "description": "Specified the argument as rest parameter (variable number of arguments)."
                            },
                            "refTo": {
                                "type": "string",
                                "description": "The name of an arguments which contains information relevant for this parameter.\nThe engineering will use this information to optimize data selection based on the underlying types.\nExample: Argument which contains the name of a control properrty may refer to an argument which holds a control reference."
                            }
                        },
                        "additionalProperties": false,
                        "required": ["name", "displayName", "description", "type", "required", "bindable"]
                    }
                }
            },
            "additionalProperties": false,
            "required": ["name", "displayName", "namespace", "description", "arguments", "returnValue"]
        },
        "dataTypes": {
            "type": "array",
            "description": "List of custom data types.",
            "items": {
                "type": "object",
                "properties": {
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": "^(?!(/)).*$",
                        "description": "Path to the schema describing the datatype."
                    }
                },
                "additionalProperties": false,
                "required": ["schema"]
            }
        },
        "languages": {
            "type": "object",
            "description": "List of language files delivered by the function.",
            "additionalProperties": {
                "description": "Key is the language and region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US'). Value is the file path or array of paths.",
                "oneOf": [
                    {
                        "type": "string",
                        "description": "Key is the language and region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US'). Value is the file path."
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "description": "List of localization files. If some keys are referenced in multiple files, the last file will win."
                        }
                    }
                ]
            }
        }
    },
    "required": ["function"],
    "additionalProperties": false
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/GetRegisteredLocales.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "GetRegisteredLocales.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "GetRegisteredLocales",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "GetRegisteredLocales",
        "visible": true,
        "category": "Locale",
        "description": "Returns the list of registered locales as array of string.",
        "returnValue": {
            "type": "tchmi:general#/definitions/Array"
        },
        "arguments": []
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/NumberToBigInt.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "NumberToBigInt.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "NumberToBigInt",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "NumberToBigInt",
        "visible": true,
        "description": "Converts a number value to bigint",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/BigInt"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/Number",
                "description": "Value to be converted",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/RemoveBinding.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "RemoveBinding.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "RemoveBinding",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "RemoveBinding",
        "description": "Removes a binding between a symbol and a control attribute setter function by name of property.",
        "category": "Binding",
        "returnValue": null,
        "arguments": [
            {
                "name": "control",
                "displayName": "Control",
                "type": "tchmi:framework#/definitions/Control",
                "description": "Control",
                "required": true,
                "bindable": false,
                "restParameter": false
            },
            {
                "name": "propertyName",
                "displayName": "PropertyName",
                "type": "tchmi:framework#/definitions/ControlPropertyName",
                "description": "The target attribute property name of control.",
                "required": true,
                "bindable": true,
                "restParameter": false,
                "refTo": "control"
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/Decrement.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "Decrement.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "Decrement",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "Decrement",
        "visible": true,
        "description": "Decrement a binding value.",
        "category": "Data Conversion",
        "injectContextObject": true,
        "waitMode": "Asynchronous",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:framework#/definitions/TcHmi.Functions.Beckhoff.Decrement.DecrementValueSymbol",
                "description": "Value to be decremented",
                "required": true,
                "bindable": true
            },
            {
                "name": "minValue",
                "displayName": "MinValue",
                "type": "tchmi:general#/definitions/Number",
                "description": "Minimum value (inclusive) to which the symbol will decremented",
                "required": false,
                "bindable": true
            },
            {
                "name": "stepWidth",
                "displayName": "StepWidth",
                "type": "tchmi:general#/definitions/Number",
                "description": "Used step width for decrement",
                "required": false,
                "bindable": true
            }
        ]
    },
    "dataTypes": [
        {
            "schema": "Schema/Types.Schema.json"
        }
    ]
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/DownloadRecipes.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "DownloadRecipes.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "DownloadRecipes",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "DownloadRecipes",
        "visible": true,
        "category": "Recipe",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "description": "Downloads one, many or all recipes of a server. \nThis needs to be triggered by a user interaction (not on load or symbol change).",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "filter",
                "displayName": "Filter",
                "type": "tchmi:framework#/definitions/MultipleRecipeReferences",
                "description": "Filter/reduce download list to some multiple recipes. \nIf this is null/unset this downloads all recipes.",
                "defaultValue": null,
                "required": true,
                "bindable": true
            },
            {
                "name": "referencedRecipeTypes",
                "displayName": "ReferencedRecipeTypes",
                "type": "tchmi:general#/definitions/Boolean",
                "description": "The export should contain referenced recipe types, too.",
                "defaultValue": false,
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/Concatenate.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "Concatenate.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "Concatenate",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "Concatenate",
        "visible": true,
        "category": "Data Conversion",
        "description": "Concatenate multiple string values.",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/String",
                "description": "Value to concatenate",
                "required": true,
                "bindable": true,
                "restParameter": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/ConvertBooleanToVisibility.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "ConvertBooleanToVisibility.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "ConvertBooleanToVisibility",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "ConvertBooleanToVisibility",
        "visible": true,
        "description": "Converts boolean values to visibility enumeration values.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:framework#/definitions/Visibility"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/Boolean",
                "description": "Value to be converted",
                "required": true,
                "bindable": true
            },
            {
                "name": "FalseValue",
                "displayName": "FalseValue",
                "type": "tchmi:framework#/definitions/Visibility",
                "description": "VisibilityValue if source value is false",
                "required": false,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/IsSafeInteger.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "IsSafeInteger.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "IsSafeInteger",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "IsSafeInteger",
        "visible": true,
        "description": "Checks if a bigint value fits safe into number.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/Boolean"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/BigInt",
                "description": "Value to be converted",
                "required": true,
                "bindable": true
            }
        ]
    }
}
