=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Framework.14.3.229/runtimes/native1.12-tchmi/Schema/FunctionDescription.Schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "URL to a schema file"
        },
        "apiVersion": {
            "description": "API Version",
            "type": "integer"
        },
        "version": {
            "type": "object",
            "description": "Version of the asset.",
            "properties": {
                "full": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "major": {
                    "type": "number",
                    "minimum": 0
                },
                "minor": {
                    "type": "number",
                    "minimum": 0
                },
                "revision": {
                    "type": "number",
                    "minimum": 0
                },
                "build": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "additionalProperties": false,
            "required": ["full", "major", "minor", "revision", "build"]
        },
        "dependencyFiles": {
            "type": "array",
            "description": "All files which will be included in the HTML file of the HMI.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "pattern": "^(?!(/)).*$",
                        "description": "Path to the file with the function directory as base path.",
                        "minLength": 1
                    },
                    "type": {
                        "type": "string",
                        "enum": ["Stylesheet", "JavaScript", "EsModule"],
                        "description": "Type of the function asset. Stylesheet, JavaScript and EsModule are supported."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description of this file."
                    }
                },
                "additionalProperties": false,
                "required": ["name", "type", "description"]
            }
        },
        "function": {
            "type": "object",
            "description": "Description for the function itself.",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The name of the function."
                },
                "namespace": {
                    "type": "string",
                    "description": "The namespace of the function."
                },
                "displayName": {
                    "type": "string",
                    "description": "Name which should be presented the user."
                },
                "visible": {
                    "type": "boolean",
                    "description": "Determine if a function is shown to the user."
                },
                "description": {
                    "type": "string",
                    "description": "A long description of this function."
                },
                "category": {
                    "type": "string",
                    "default": "Other",
                    "description": "Name of the area this function will be listed in the creator."
                },
                "injectContextObject": {
                    "type": "boolean",
                    "description": "Adds a context object to the function as the first parameter."
                },
                "waitMode": {
                    "type": "string",
                    "default": "Synchronous",
                    "enum": ["Synchronous", "Asynchronous"],
                    "description": "Tells the system if the function is finished synchronous or if the user will call a feedback function in the context object of the context object to signal finish."
                },
                "returnValue": {
                    "description": "Return value type as a tchmi reference name or null if the function has no return value.",
                    "anyOf": [
                        {
                            "description": "Return value type as a tchmi reference name.",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "pattern": "^tchmi:",
                                    "description": "Type from the return value."
                                },
                                "description": {
                                    "type": "string",
                                    "description": "A long description of the return value."
                                }
                            },
                            "additionalProperties": false
                        },
                        {
                            "description": "The function has no return value.",
                            "type": "null"
                        }
                    ]
                },
                "arguments": {
                    "type": "array",
                    "description": "Function arguments.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "minLength": 1,
                                "description": "Variable name in the function."
                            },
                            "displayName": {
                                "type": "string",
                                "description": "Name which should be presented the user."
                            },
                            "type": {
                                "type": "string",
                                "minLength": 6,
                                "pattern": "^tchmi:",
                                "description": "Information about the expected type as a tchmi reference name."
                            },
                            "description": {
                                "type": "string",
                                "description": "A long description of this argument."
                            },
                            "required": {
                                "type": "boolean",
                                "description": "This parameter is mandatory for this function."
                            },
                            "bindable": {
                                "type": "boolean",
                                "description": "This parameter can be binded to a symbol."
                            },
                            "allowControlAttributeBindingOptions": {
                                "type": "boolean",
                                "description": "This parameter can have the same binding options as a control attribute."
                            },
                            "allowSymbolReferenceWatchDelegation": {
                                "type": "boolean",
                                "description": "Determines if symbol references injected via this parameter will be watched by the function itself if 'delegatedWatch: true' is defined in the context object when calling the function."
                            },
                            "asReference": {
                                "type": "boolean",
                                "description": "TcHmiCreator ui state. Do not manipulate."
                            },
                            "defaultValue": {
                                "description": "This value will be used as initial value while function is generated in engineering."
                            },
                            "restParameter": {
                                "type": "boolean",
                                "description": "Specified the argument as rest parameter (variable number of arguments)."
                            },
                            "refTo": {
                                "type": "string",
                                "description": "The name of an arguments which contains information relevant for this parameter.\nThe engineering will use this information to optimize data selection based on the underlying types.\nExample: Argument which contains the name of a control properrty may refer to an argument which holds a control reference."
                            }
                        },
                        "additionalProperties": false,
                        "required": ["name", "displayName", "description", "type", "required", "bindable"]
                    }
                }
            },
            "additionalProperties": false,
            "required": ["name", "displayName", "namespace", "description", "arguments", "returnValue"]
        },
        "dataTypes": {
            "type": "array",
            "description": "List of custom data types.",
            "items": {
                "type": "object",
                "properties": {
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": "^(?!(/)).*$",
                        "description": "Path to the schema describing the datatype."
                    }
                },
                "additionalProperties": false,
                "required": ["schema"]
            }
        },
        "languages": {
            "type": "object",
            "description": "List of language files delivered by the function.",
            "additionalProperties": {
                "description": "Key is the language and region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US'). Value is the file path or array of paths.",
                "oneOf": [
                    {
                        "type": "string",
                        "description": "Key is the language and region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US'). Value is the file path."
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "description": "List of localization files. If some keys are referenced in multiple files, the last file will win."
                        }
                    }
                ]
            }
        }
    },
    "required": ["function"],
    "additionalProperties": false
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/EnumToMemberName.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "EnumToMemberName.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "EnumToMemberName",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "EnumToMemberName",
        "visible": true,
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "description": "Resolves the corresponding enum member string of the current value of a given enum symbol.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "symbol",
                "displayName": "Symbol",
                "type": "tchmi:framework#/definitions/Symbol",
                "description": "The target symbol.",
                "required": true,
                "bindable": true,
                "allowSymbolReferenceWatchDelegation": true,
                "restParameter": false
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/BigIntToNumber.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "BigIntToNumber.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "BigIntToNumber",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "BigIntToNumber",
        "visible": true,
        "description": "Converts a bigint value to number",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/Number"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/BigInt",
                "description": "Value to be converted",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/SetElementByIndex.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "SetElementByIndex.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "SetElementByIndex",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "SetElementByIndex",
        "visible": true,
        "description": "Inserts the value at the array index position.",
        "category": "Data Conversion",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "arraySymbol",
                "displayName": "ArraySymbol",
                "type": "tchmi:framework#/definitions/Symbol",
                "description": "Value to be trimmed",
                "required": true,
                "bindable": true
            },
            {
                "name": "index",
                "displayName": "Index",
                "type": "tchmi:framework#/definitions/PositiveNumber",
                "description": "Index",
                "required": true,
                "bindable": true
            },
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/Any",
                "description": "Value to write to the array.",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/FormatString.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "FormatString.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "FormatString",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "FormatString",
        "visible": true,
        "description": "Format a string. \nPlaceholder syntax in format string: '{' to begin placeholder, optional parameter-index with | as seperator, description and '}' to close the placeholder. \nExample: {0|.1f}",
        "category": "Formatting",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "formatString",
                "displayName": "FormatString",
                "type": "tchmi:general#/definitions/String",
                "description": "FormatString with placeholder to be formatted",
                "required": true,
                "bindable": true
            },
            {
                "name": "args",
                "displayName": "Args",
                "type": "tchmi:general#/definitions/Any",
                "description": "Argument to format the placeholder in formatString",
                "required": true,
                "bindable": true,
                "restParameter": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/ConvertBooleanToEnum.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "ConvertBooleanToEnum.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "ConvertBooleanToEnum",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "ConvertBooleanToEnum",
        "visible": true,
        "description": "Converts boolean values to enumeration values.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/Boolean",
                "description": "Value to be converted",
                "required": true,
                "bindable": true
            },
            {
                "name": "trueValue",
                "displayName": "TrueValue",
                "type": "tchmi:general#/definitions/String",
                "description": "Return value if source value is true",
                "required": true,
                "bindable": true
            },
            {
                "name": "falseValue",
                "displayName": "FalseValue",
                "type": "tchmi:general#/definitions/String",
                "description": "Return value if source value is false",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/DownloadRecipeTypes.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "DownloadRecipeTypes.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "DownloadRecipeTypes",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "DownloadRecipeTypes",
        "visible": true,
        "category": "Recipe",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "description": "Downloads one, many or all recipe types of a server. \nThis needs to be triggered by a user interaction (not on load or symbol change).",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "filter",
                "displayName": "Filter",
                "type": "tchmi:framework#/definitions/MultipleRecipeTypeReferences",
                "description": "Filter/reduce download list to some multiple recipe types. \nIf this is null/unset this downloads all recipe types.",
                "defaultValue": null,
                "required": true,
                "bindable": true
            },
            {
                "name": "referencedRecipeTypes",
                "displayName": "ReferencedRecipeTypes",
                "type": "tchmi:general#/definitions/Boolean",
                "description": "The export should contain referenced recipe types, too.",
                "defaultValue": false,
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Controls.14.3.234/runtimes/native1.12-tchmi/TcHmiEventGrid/EventClassesProvider/EventClassesProvider.function.json
{
    "$schema": "../../../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.234.0",
        "major": 14,
        "minor": 3,
        "build": 234,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "EventClassesProvider.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "EventClassesProvider",
        "namespace": "TcHmi.Controls.Beckhoff.TcHmiEventGrid",
        "displayName": "EventClassesProvider",
        "visible": false,
        "description": "Provides classes for Datagrid rows depending on event properties like type, severity and alarm state.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/Array"
        },
        "arguments": [
            {
                "name": "rowValue",
                "displayName": "RowValue",
                "type": "tchmi:general#/definitions/Any",
                "description": "The value of the row",
                "required": true,
                "bindable": true
            },
            {
                "name": "dataIndex",
                "displayName": "DataIndex",
                "type": "tchmi:general#/definitions/Number",
                "description": "The index of the row in the srcData",
                "required": false,
                "bindable": true
            },
            {
                "name": "rowNumber",
                "displayName": "RowNumber",
                "type": "tchmi:general#/definitions/Number",
                "description": "The rowNumber of the row after sorting",
                "required": false,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/SetAutoOpenSystemKeyboard.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "SetAutoOpenSystemKeyboard.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "SetAutoOpenSystemKeyboard",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "SetAutoOpenSystemKeyboard",
        "description": "Sets if the system keyboard should open on focus of a textarea or input element.",
        "category": "Keyboard",
        "returnValue": null,
        "arguments": [
            {
                "name": "autoOpenSystemKeyboard",
                "displayName": "AutoOpenSystemKeyboard",
                "type": "tchmi:general#/definitions/Boolean",
                "description": "AutoOpenSystemKeyboard",
                "required": true,
                "bindable": true,
                "restParameter": false
            }
        ]
    }
}
