=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Framework.14.3.229/runtimes/native1.12-tchmi/Schema/FunctionDescription.Schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "URL to a schema file"
        },
        "apiVersion": {
            "description": "API Version",
            "type": "integer"
        },
        "version": {
            "type": "object",
            "description": "Version of the asset.",
            "properties": {
                "full": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$"
                },
                "major": {
                    "type": "number",
                    "minimum": 0
                },
                "minor": {
                    "type": "number",
                    "minimum": 0
                },
                "revision": {
                    "type": "number",
                    "minimum": 0
                },
                "build": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "additionalProperties": false,
            "required": ["full", "major", "minor", "revision", "build"]
        },
        "dependencyFiles": {
            "type": "array",
            "description": "All files which will be included in the HTML file of the HMI.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "pattern": "^(?!(/)).*$",
                        "description": "Path to the file with the function directory as base path.",
                        "minLength": 1
                    },
                    "type": {
                        "type": "string",
                        "enum": ["Stylesheet", "JavaScript", "EsModule"],
                        "description": "Type of the function asset. Stylesheet, JavaScript and EsModule are supported."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description of this file."
                    }
                },
                "additionalProperties": false,
                "required": ["name", "type", "description"]
            }
        },
        "function": {
            "type": "object",
            "description": "Description for the function itself.",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The name of the function."
                },
                "namespace": {
                    "type": "string",
                    "description": "The namespace of the function."
                },
                "displayName": {
                    "type": "string",
                    "description": "Name which should be presented the user."
                },
                "visible": {
                    "type": "boolean",
                    "description": "Determine if a function is shown to the user."
                },
                "description": {
                    "type": "string",
                    "description": "A long description of this function."
                },
                "category": {
                    "type": "string",
                    "default": "Other",
                    "description": "Name of the area this function will be listed in the creator."
                },
                "injectContextObject": {
                    "type": "boolean",
                    "description": "Adds a context object to the function as the first parameter."
                },
                "waitMode": {
                    "type": "string",
                    "default": "Synchronous",
                    "enum": ["Synchronous", "Asynchronous"],
                    "description": "Tells the system if the function is finished synchronous or if the user will call a feedback function in the context object of the context object to signal finish."
                },
                "returnValue": {
                    "description": "Return value type as a tchmi reference name or null if the function has no return value.",
                    "anyOf": [
                        {
                            "description": "Return value type as a tchmi reference name.",
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "pattern": "^tchmi:",
                                    "description": "Type from the return value."
                                },
                                "description": {
                                    "type": "string",
                                    "description": "A long description of the return value."
                                }
                            },
                            "additionalProperties": false
                        },
                        {
                            "description": "The function has no return value.",
                            "type": "null"
                        }
                    ]
                },
                "arguments": {
                    "type": "array",
                    "description": "Function arguments.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "minLength": 1,
                                "description": "Variable name in the function."
                            },
                            "displayName": {
                                "type": "string",
                                "description": "Name which should be presented the user."
                            },
                            "type": {
                                "type": "string",
                                "minLength": 6,
                                "pattern": "^tchmi:",
                                "description": "Information about the expected type as a tchmi reference name."
                            },
                            "description": {
                                "type": "string",
                                "description": "A long description of this argument."
                            },
                            "required": {
                                "type": "boolean",
                                "description": "This parameter is mandatory for this function."
                            },
                            "bindable": {
                                "type": "boolean",
                                "description": "This parameter can be binded to a symbol."
                            },
                            "allowControlAttributeBindingOptions": {
                                "type": "boolean",
                                "description": "This parameter can have the same binding options as a control attribute."
                            },
                            "allowSymbolReferenceWatchDelegation": {
                                "type": "boolean",
                                "description": "Determines if symbol references injected via this parameter will be watched by the function itself if 'delegatedWatch: true' is defined in the context object when calling the function."
                            },
                            "asReference": {
                                "type": "boolean",
                                "description": "TcHmiCreator ui state. Do not manipulate."
                            },
                            "defaultValue": {
                                "description": "This value will be used as initial value while function is generated in engineering."
                            },
                            "restParameter": {
                                "type": "boolean",
                                "description": "Specified the argument as rest parameter (variable number of arguments)."
                            },
                            "refTo": {
                                "type": "string",
                                "description": "The name of an arguments which contains information relevant for this parameter.\nThe engineering will use this information to optimize data selection based on the underlying types.\nExample: Argument which contains the name of a control properrty may refer to an argument which holds a control reference."
                            }
                        },
                        "additionalProperties": false,
                        "required": ["name", "displayName", "description", "type", "required", "bindable"]
                    }
                }
            },
            "additionalProperties": false,
            "required": ["name", "displayName", "namespace", "description", "arguments", "returnValue"]
        },
        "dataTypes": {
            "type": "array",
            "description": "List of custom data types.",
            "items": {
                "type": "object",
                "properties": {
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": "^(?!(/)).*$",
                        "description": "Path to the schema describing the datatype."
                    }
                },
                "additionalProperties": false,
                "required": ["schema"]
            }
        },
        "languages": {
            "type": "object",
            "description": "List of language files delivered by the function.",
            "additionalProperties": {
                "description": "Key is the language and region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US'). Value is the file path or array of paths.",
                "oneOf": [
                    {
                        "type": "string",
                        "description": "Key is the language and region (optionally) as described in ISO 639/BCP 47 (Examples: 'en', 'en-US'). Value is the file path."
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "description": "List of localization files. If some keys are referenced in multiple files, the last file will win."
                        }
                    }
                ]
            }
        }
    },
    "required": ["function"],
    "additionalProperties": false
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/TeachRecipe.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "TeachRecipe.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "TeachRecipe",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "TeachRecipe",
        "visible": true,
        "category": "Recipe",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "description": "Reads the current values which are referenced from a base recipe and write it into the same recipe.",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "recipeReference",
                "displayName": "RecipeReference",
                "type": "tchmi:framework#/definitions/RecipeReference",
                "description": "Reference (path + '::' + name) of the recipe",
                "defaultValue": null,
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/SetLocaleEx.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "SetLocaleEx.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "SetLocaleEx",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "SetLocaleEx",
        "visible": true,
        "category": "Locale",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "description": "Sets the application locale. \nThe function waits for loading of the language files.",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "locale",
                "displayName": "Locale",
                "type": "tchmi:general#/definitions/ProjectLocale",
                "description": "Locale",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/CreateBinding.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "CreateBinding.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "CreateBinding",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "CreateBinding",
        "description": "Creates a binding between a symbol and a control attribute setter function by name of property.",
        "category": "Binding",
        "returnValue": null,
        "arguments": [
            {
                "name": "control",
                "displayName": "Control",
                "type": "tchmi:framework#/definitions/Control",
                "description": "Control",
                "required": true,
                "bindable": false,
                "restParameter": false
            },
            {
                "name": "propertyName",
                "displayName": "PropertyName",
                "type": "tchmi:framework#/definitions/ControlPropertyName",
                "description": "The target attribute property name of control.",
                "required": true,
                "bindable": true,
                "restParameter": false,
                "refTo": "control"
            },
            {
                "name": "symbol",
                "displayName": "Symbol",
                "type": "tchmi:framework#/definitions/Symbol",
                "description": "The target symbol.",
                "required": true,
                "bindable": true,
                "allowControlAttributeBindingOptions": true,
                "refTo": "control",
                "restParameter": false
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/Increment.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "Increment.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "Increment",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "Increment",
        "visible": true,
        "description": "Increment a binding value.",
        "category": "Data Conversion",
        "injectContextObject": true,
        "waitMode": "Asynchronous",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:framework#/definitions/TcHmi.Functions.Beckhoff.Increment.IncrementValueSymbol",
                "description": "Value to be incremented",
                "required": true,
                "bindable": true
            },
            {
                "name": "maxValue",
                "displayName": "MaxValue",
                "type": "tchmi:general#/definitions/Number",
                "description": "Maximum value (inclusive) to which the symbol will incremented",
                "required": false,
                "bindable": true
            },
            {
                "name": "stepWidth",
                "displayName": "StepWidth",
                "type": "tchmi:general#/definitions/Number",
                "description": "Used step width for increment",
                "required": false,
                "bindable": true
            }
        ]
    },
    "dataTypes": [
        {
            "schema": "Schema/Types.Schema.json"
        }
    ]
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/TeachAsNewRecipe.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "TeachAsNewRecipe.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "TeachAsNewRecipe",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "TeachAsNewRecipe",
        "visible": true,
        "category": "Recipe",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "description": "Reads the current values which are referenced from a base recipe and write it into a new recipe.",
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "recipeReference",
                "displayName": "RecipeReference",
                "type": "tchmi:framework#/definitions/RecipeReference",
                "description": "Reference (path + '::' + name) of the recipe",
                "defaultValue": null,
                "required": true,
                "bindable": true
            },
            {
                "name": "newRecipeName",
                "displayName": "NewRecipeName",
                "type": "tchmi:general#/definitions/String",
                "description": "New name of the recipe",
                "defaultValue": "newRecipe",
                "required": true,
                "bindable": true
            },
            {
                "name": "newRecipePath",
                "displayName": "NewRecipePath",
                "type": "tchmi:general#/definitions/String",
                "description": "New path of the recipe",
                "defaultValue": null,
                "required": false,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/SymbolExists.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "SymbolExists.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "SymbolExists",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "SymbolExists",
        "description": "Checks if a specific symbol exists.",
        "category": "Symbol",
        "waitMode": "Asynchronous",
        "injectContextObject": true,
        "returnValue": null,
        "arguments": [
            {
                "name": "ctx",
                "displayName": "ctx",
                "type": "tchmi:framework#/definitions/ContextReference",
                "description": "Context Reference",
                "required": true,
                "bindable": false
            },
            {
                "name": "symbol",
                "displayName": "Symbol",
                "type": "tchmi:framework#/definitions/Symbol",
                "description": "The target symbol.",
                "required": true,
                "bindable": true,
                "restParameter": false
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/ToLowerCase.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "ToLowerCase.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "ToLowerCase",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "ToLowerCase",
        "visible": true,
        "description": "Converts string value to lowercase.",
        "category": "Data Conversion",
        "returnValue": {
            "type": "tchmi:general#/definitions/String"
        },
        "arguments": [
            {
                "name": "value",
                "displayName": "Value",
                "type": "tchmi:general#/definitions/String",
                "description": "Value to lowercase",
                "required": true,
                "bindable": true
            }
        ]
    }
}

=== Keiji01/TwinCAT3/DemoKIT TF2000/DemoKIT_TF2000/Packages/Beckhoff.TwinCAT.HMI.Functions.14.3.229/runtimes/native1.12-tchmi/SetAttributeToThemeValue.function.json
{
    "$schema": "../TcHmiFramework/Schema/FunctionDescription.Schema.json",
    "apiVersion": 1,
    "version": {
        "full": "14.3.229.0",
        "major": 14,
        "minor": 3,
        "build": 229,
        "revision": 0
    },
    "dependencyFiles": [
        {
            "name": "SetAttributeToThemeValue.js",
            "type": "JavaScript",
            "description": ""
        }
    ],
    "function": {
        "name": "SetAttributeToThemeValue",
        "namespace": "TcHmi.Functions.Beckhoff",
        "displayName": "SetAttributeToThemeValue",
        "description": "Sets the default value of a property and change it (if needed) on theme change.",
        "category": "Theme",
        "returnValue": null,
        "arguments": [
            {
                "name": "control",
                "displayName": "Control",
                "type": "tchmi:framework#/definitions/Control",
                "description": "Control to set the default value on it.",
                "required": true,
                "bindable": false,
                "restParameter": false
            },
            {
                "name": "propertyName",
                "displayName": "PropertyName",
                "type": "tchmi:framework#/definitions/ControlPropertyName",
                "description": "Name of the property to set default.",
                "required": true,
                "bindable": true,
                "restParameter": false,
                "refTo": "control"
            }
        ]
    }
}
